[build-system]
requires = ["setuptools", "wheel", "radvel", "numpy"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]
name = 'sossisse'
authors = [
    {name = 'Neil Cook', email = 'neil.james.cook@gmail.com'},
]
description = 'SOSSISSE - SOSS Inspired SpectroScopic Extraction'
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = 'LICENSE'}
requires-python = "==3.12.*"
dependencies = [
    "jwst==1.20.2",
    # "crds==12.1.1",
    "numpy==2.3.4",
    "astropy==7.2.0",
    "ipython==8.32.0",
    "scipy==1.17.1",
    "matplotlib==3.10.8",
    "numexpr==2.14.1",
    "tqdm==4.67.3",
    "h5py==3.15.1",
    "ruamel.yaml==0.19.1",
    "wpca==0.1",
    "scikit-image==0.26.0",
    "scikit-learn==1.8.0",
    "statsmodels==0.14.6",

    "astraeus-io @ git+https://github.com/kevin218/Astraeus.git"
]

[project.urls]
Homepage = 'http://apero.exoplanets.ca'
Repository = 'https://github.com/njcuk9999/sossisse'

[project.scripts]
sossisse_setup = "sossisse.recipes.run_setup:run"
sossisse_run = "sossisse.recipes.run_sossisse:run"

[project.optional-dependencies]
full = ["aperocore @ git+https://github.com/njcuk9999/apero-drs.git@v0.8.running#subdirectory=apero-core",
        "pastasoss @ git+https://github.com/njcuk9999/pastasoss.git"]
dev = ["aperocore", "pastasoss"]


[tool.setuptools]
packages = ["sossisse", "sossisse.core", "sossisse.general",
            "sossisse.instruments", "sossisse.recipes"]
include-package-data = true

[tool.setuptools.package-data]
"sossisse" = ["info.yaml"]